server:
  port: 8081
  servlet:
    context-path: /blog
spring:
  application:
      name: zxc-blog
  profiles:
    active: local
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zxc_blog?characterEncoding=UTF-8&useSSL=false&&serverTimezone=GMT
      username: root
      password: root
      initialize: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-wait-millis: 30000
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 20000
      min-evictable-idle-time-millis: 28700
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db.changelog.xml
