server:
  port: 8081
  servlet:
    context-path: /blog
spring:
  cloud:
    config:
      uri: http://localhost:8082
  application:
      name: zxc-blog
  profiles:
    active: local
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.230.10:3306/zxc_blog?characterEncoding=UTF-8&useSSL=false&&serverTimezone=GMT
      username: ${mysql.username}
      password: ${mysql.password}
      initialize: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-wait-millis: 30000
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 20000
      min-evictable-idle-time-millis: 28700
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db.changelog.xml
  data:
    mongodb:
      host: ${mongo.host}
      username: ${mongo.username}
      password: ${mongo.password}
  redis:
    host: ${redis.host}
    database: 0
